[base]
workshop = []
parameters = [
    "-window",
    "-noPause",
    "-noPauseAudio",
]

# executable = "arma3_x64"        # Default: "arma3_x64"
# file_patching = true # Default: true
# binarize = false # Default: false
# rapify = true # Default: true

presets = []
dlc = []
optionals = []


[default]
extends = "base"
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3
    "3499977893", # Advanced Developer Tools
    "1779063631", # ZEN
]
dlc = []


[test]
extends = "default"
mission = "test.VR"


[arsenal]
extends = "default"
mission = "arsenal.VR"

[csc]
extends = "default"
mission = "CSC.Altis"

[intel]
extends = "default"
mission = "intel.VR"

[ula]
extends = "default"
mission = "ULA-Dedicated-MP-Test.stratis"
